# Generated by Django 4.0.3 on 2022-04-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiAvatarUser',
        ),
    ]
