# Generated by Django 4.0.3 on 2022-03-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_alter_auto_patente_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problema',
            name='egreso',
        ),
        migrations.AlterField(
            model_name='auto',
            name='patente',
            field=models.CharField(max_length=7),
        ),
    ]
