# Generated by Django 4.0.3 on 2022-03-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0006_remove_problema_egreso_alter_auto_patente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
