# Generated by Django 4.0.3 on 2022-03-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0007_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='arreglado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='problema',
            name='ingreso',
            field=models.DateField(),
        ),
    ]
