# Generated by Django 4.0.3 on 2022-03-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0008_alter_problema_arreglado_alter_problema_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problema',
            name='arreglado',
        ),
        migrations.RemoveField(
            model_name='problema',
            name='ingreso',
        ),
    ]
