# Generated by Django 4.0.3 on 2022-04-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0010_miavataruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiAvatarUser',
        ),
    ]
